@Test
    public void createPatient() throws Exception {
        IGenericClient client = FhirServiceUtil.getFhirDstu2Client();

        Patient patient = FhirDstu2Util.getPatient();
        MethodOutcome methodOutcome = client.create().resource(patient).execute();
        String id = methodOutcome.getId().getIdPart();
        patient.setId(id);

        System.out.println("Patient id generated by server is: " + id);
    }